version: 2
updates:
  - package-ecosystem: terraform
    directories:
      - /terraform/bootstrap
      - /terraform/environments/dev
      - /terraform/environments/prod
    schedule:
      interval: monthly
    groups:
      terraform-providers:
        patterns:
          - "*"
    ignore:
      - dependency-name: hashicorp/azurerm
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 3

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3
